name: Paths Filter

on:
  workflow_call:
    outputs:
      backend:
        description: "Backend changes detected"
        value: ${{ jobs.filter.outputs.backend }}
      frontend:
        description: "Frontend changes detected"
        value: ${{ jobs.filter.outputs.frontend }}

permissions:
  contents: read

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          filters: |
            backend:
              - 'server/**'
              - '.github/workflows/backend-check.yml'
            frontend:
              - 'client/**'
              - '.github/workflows/frontend-check.yml'